CREATE TABLE IF NOT EXISTS RAW_AVSTACK_FLIGHTS (
    INGEST_ID STRING,
    INGESTED_AT TIMESTAMP_NTZ,
    FLIGHT_DATE DATE,
    FLIGHT_IATA STRING,
    DEP_IATA STRING,
    ARR_IATA STRING,
    RECORD VARIANT,
    SOURCE STRING
);

CREATE TABLE IF NOT EXISTS DIM_AIRPORT (
    AIRPORT_IATA STRING PRIMARY KEY,
    AIRPORT_NAME STRING,
    TIMEZONE STRING,
    ICAO STRING,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS DIM_AIRLINE (
    AIRLINE_IATA STRING PRIMARY KEY,
    AIRLINE_ICAO STRING,
    AIRLINE_NAME STRING,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS FACT_FLIGHT (
    FLIGHT_NK STRING PRIMARY KEY,
    FLIGHT_DATE DATE,
    FLIGHT_STATUS STRING,
    AIRLINE_IATA STRING,
    FLIGHT_NUMBER STRING,
    FLIGHT_IATA STRING,
    FLIGHT_ICAO STRING,
    DEP_IATA STRING,
    ARR_IATA STRING,
    DEP_TERMINAL STRING,
    DEP_GATE STRING,
    ARR_TERMINAL STRING,
    ARR_GATE STRING,
    DEP_DELAY_MIN INTEGER,
    ARR_DELAY_MIN INTEGER,
    DEP_SCHEDULED_UTC TIMESTAMP_NTZ,
    DEP_ESTIMATED_UTC TIMESTAMP_NTZ,
    DEP_ACTUAL_UTC TIMESTAMP_NTZ,
    ARR_SCHEDULED_UTC TIMESTAMP_NTZ,
    ARR_ESTIMATED_UTC TIMESTAMP_NTZ,
    ARR_ACTUAL_UTC TIMESTAMP_NTZ,
    LAST_SEEN_AT TIMESTAMP_NTZ,
    SOURCE STRING
);
