MERGE INTO DIM_AIRPORT AS t
USING (
    SELECT
        %s AS AIRPORT_IATA,
        %s AS AIRPORT_NAME,
        %s AS TIMEZONE,
        %s AS ICAO
) AS s
ON t.AIRPORT_IATA = s.AIRPORT_IATA
WHEN MATCHED THEN UPDATE SET
    AIRPORT_NAME = s.AIRPORT_NAME,
    TIMEZONE = s.TIMEZONE,
    ICAO = s.ICAO,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    AIRPORT_IATA, AIRPORT_NAME, TIMEZONE, ICAO, UPDATED_AT
) VALUES (
    s.AIRPORT_IATA, s.AIRPORT_NAME, s.TIMEZONE, s.ICAO, CURRENT_TIMESTAMP()
);
