MERGE INTO DIM_AIRLINE AS t
USING (
    SELECT
        %s AS AIRLINE_IATA,
        %s AS AIRLINE_ICAO,
        %s AS AIRLINE_NAME
) AS s
ON t.AIRLINE_IATA = s.AIRLINE_IATA
WHEN MATCHED THEN UPDATE SET
    AIRLINE_ICAO = s.AIRLINE_ICAO,
    AIRLINE_NAME = s.AIRLINE_NAME,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    AIRLINE_IATA, AIRLINE_ICAO, AIRLINE_NAME, UPDATED_AT
) VALUES (
    s.AIRLINE_IATA, s.AIRLINE_ICAO, s.AIRLINE_NAME, CURRENT_TIMESTAMP()
);
