MERGE INTO FACT_FLIGHT AS t
USING (
    SELECT
        %s AS FLIGHT_NK,
        %s AS FLIGHT_DATE,
        %s AS FLIGHT_STATUS,
        %s AS AIRLINE_IATA,
        %s AS FLIGHT_NUMBER,
        %s AS FLIGHT_IATA,
        %s AS FLIGHT_ICAO,
        %s AS DEP_IATA,
        %s AS ARR_IATA,
        %s AS DEP_TERMINAL,
        %s AS DEP_GATE,
        %s AS ARR_TERMINAL,
        %s AS ARR_GATE,
        %s AS DEP_DELAY_MIN,
        %s AS ARR_DELAY_MIN,
        %s AS DEP_SCHEDULED_UTC,
        %s AS DEP_ESTIMATED_UTC,
        %s AS DEP_ACTUAL_UTC,
        %s AS ARR_SCHEDULED_UTC,
        %s AS ARR_ESTIMATED_UTC,
        %s AS ARR_ACTUAL_UTC,
        %s AS SOURCE
) AS s
ON t.FLIGHT_NK = s.FLIGHT_NK
WHEN MATCHED THEN UPDATE SET
    FLIGHT_DATE = s.FLIGHT_DATE,
    FLIGHT_STATUS = s.FLIGHT_STATUS,
    AIRLINE_IATA = s.AIRLINE_IATA,
    FLIGHT_NUMBER = s.FLIGHT_NUMBER,
    FLIGHT_IATA = s.FLIGHT_IATA,
    FLIGHT_ICAO = s.FLIGHT_ICAO,
    DEP_IATA = s.DEP_IATA,
    ARR_IATA = s.ARR_IATA,
    DEP_TERMINAL = s.DEP_TERMINAL,
    DEP_GATE = s.DEP_GATE,
    ARR_TERMINAL = s.ARR_TERMINAL,
    ARR_GATE = s.ARR_GATE,
    DEP_DELAY_MIN = s.DEP_DELAY_MIN,
    ARR_DELAY_MIN = s.ARR_DELAY_MIN,
    DEP_SCHEDULED_UTC = s.DEP_SCHEDULED_UTC,
    DEP_ESTIMATED_UTC = s.DEP_ESTIMATED_UTC,
    DEP_ACTUAL_UTC = s.DEP_ACTUAL_UTC,
    ARR_SCHEDULED_UTC = s.ARR_SCHEDULED_UTC,
    ARR_ESTIMATED_UTC = s.ARR_ESTIMATED_UTC,
    ARR_ACTUAL_UTC = s.ARR_ACTUAL_UTC,
    LAST_SEEN_AT = CURRENT_TIMESTAMP(),
    SOURCE = s.SOURCE
WHEN NOT MATCHED THEN INSERT (
    FLIGHT_NK, FLIGHT_DATE, FLIGHT_STATUS, AIRLINE_IATA, FLIGHT_NUMBER,
    FLIGHT_IATA, FLIGHT_ICAO, DEP_IATA, ARR_IATA, DEP_TERMINAL, DEP_GATE,
    ARR_TERMINAL, ARR_GATE, DEP_DELAY_MIN, ARR_DELAY_MIN,
    DEP_SCHEDULED_UTC, DEP_ESTIMATED_UTC, DEP_ACTUAL_UTC,
    ARR_SCHEDULED_UTC, ARR_ESTIMATED_UTC, ARR_ACTUAL_UTC,
    LAST_SEEN_AT, SOURCE
) VALUES (
    s.FLIGHT_NK, s.FLIGHT_DATE, s.FLIGHT_STATUS, s.AIRLINE_IATA, s.FLIGHT_NUMBER,
    s.FLIGHT_IATA, s.FLIGHT_ICAO, s.DEP_IATA, s.ARR_IATA, s.DEP_TERMINAL, s.DEP_GATE,
    s.ARR_TERMINAL, s.ARR_GATE, s.DEP_DELAY_MIN, s.ARR_DELAY_MIN,
    s.DEP_SCHEDULED_UTC, s.DEP_ESTIMATED_UTC, s.DEP_ACTUAL_UTC,
    s.ARR_SCHEDULED_UTC, s.ARR_ESTIMATED_UTC, s.ARR_ACTUAL_UTC,
    CURRENT_TIMESTAMP(), s.SOURCE
);
